### ISSUE TITLE
'glue/sparkui:latest' missing in Docker hub

### ISSUE THREAD

**Issue by frank-io** [aws-samples/aws-glue-samples#102]
Hi all,

I got the error below when trying to load the spark ui with Docker. Anyone else has the same issue? Thanks
```
Loading Spark log in s3a://path-to-log
Unable to find image 'glue/sparkui:latest' locally
docker: Error response from daemon: pull access denied for glue/sparkui, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

**Comment by moomindani** [comment]
This image is not hosted in Docker Hub. As you can see in README, you can build docker image using Dockerfile and use it.

**Comment by cvargas-xbrein** [comment]
> Hi all,
> 
> I got the error below when trying to load the spark ui with Docker. Anyone else has the same issue? Thanks
> 
> ```
> Loading Spark log in s3a://path-to-log
> Unable to find image 'glue/sparkui:latest' locally
> docker: Error response from daemon: pull access denied for glue/sparkui, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
> See 'docker run --help'.
> ```

try add this en dockerr run ,  works for me:   
` /bin/bash -c "/opt/spark/bin/spark-class org.apache.spark.deploy.history.HistoryServer"`

**Comment by moomindani** [comment]
I guess you skipped docker build.
