### ISSUE TITLE
Spark UI Glue 4.0 Logging Not Working?

### ISSUE THREAD

**Issue by AlJohri** [aws-samples/aws-glue-samples#136]
I get this message and not more logs when I run the Glue 4.0 Spark UI container:

```
log4j:WARN No appenders could be found for logger (org.apache.spark.deploy.history.HistoryServer).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

**Comment by moomindani** [comment]
Thank you for the feedback, and suggestion for the fix.
I have added similar log4j.properties to fix the issue in [this commit](https://github.com/aws-samples/aws-glue-samples/commit/872e82c4831591ae3de8f648d680f94bf3f51707).
