### ISSUE TITLE
Add description about spark dependecies version

### ISSUE THREAD

**Issue by nikita-sheremet-java-developer** [aws-samples/aws-glue-samples#14]
Scala examples were added to the project. But what spark dependecies are used? What versions do they have?

For example it uses `spark-sql` but what version is? What scala naguage version is? Could you please add this information to the project readme.md or link where this information is placed?

**Comment by mohitsax** [comment]
Thanks for using AWS Glue. We support Apache Spark version 2.2.1 and Scala version 2.11 as of today (June 6, 2018). We announced the support on April 10. Please find more details here: https://aws.amazon.com/about-aws/whats-new/2018/04/aws-glue-now-supports-apache-spark-221/
