### ISSUE TITLE
unclear instructions 

### ISSUE THREAD

**Issue by angelarw** [aws-samples/aws-glue-samples#2]
in this example:
https://github.com/awslabs/aws-glue-samples/blob/master/examples/join_and_relationalize.md
"1. Crawl our sample dataset" can you specify if user is supposed to copy the dataset from your sample bucket to their own bucket before proceeding to crawl, or just use your bucket as the source?  the latter doesn't work. I got 
"[626034be-45ee-4e8d-ae26-e985e8131ff9] ERROR : Error Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: F24B84B451EAEC7A) retrieving file at s3://awsglue-datasets/examples/us-legislators/house/persons.json. Tables created did not infer schemas from this file." 

also there's a typo in the s3 path (you have a dot at the end)
"s3://awsglue-datasets/examples/us-legislators."

**Comment by angelarw** [comment]
oh i think the problem is the IAM role with the glue managed policy gives access to
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::crawler-public*",
                "arn:aws:s3:::aws-glue-*"
            ]
        },
but your sample bucket starts with "awsglue-" so it doesn't match

**Comment by mashah** [comment]
Thanks for pointing this out!

We will fix this in the documentation.

**Comment by alecswan** [comment]
I just ran into the same problem. AWS managed policy AWSGlueServiceRole provides access to "arn:aws:s3:::aws-glue-*/*". Would it be possible to move or copy data samples from s3://awsglue-datasets/examples to s3://aws-glue-datasets/examples?

**Comment by AdamShechter9** [comment]
Running into same error as angelarw.
`[49eaba68-d5c2-4245-803a-6ec9736422ea] ERROR : Error Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 8FF7A6AB88E7D7FA; S3 Extended Request ID: Wqplw7A9+PEVI5Cpg0hCwgm7UPEstv3Vbj+7sWDEo1/+6GaiFff2TE471wci3QR+yhZeO7NEtqA=) retrieving file at s3://awsglue-datasets/examples/us-legislators/all/persons.json. Tables created did not infer schemas from this file.`

poorly done examples/instructions.

**Comment by Alvarosantoma** [comment]
I also had the same problem but it turned out that when you select the path for their bucket you have to specify that it an external path.

**Comment by pradeepn91** [comment]
I have the same  as well, do we have to make to s3 bucket public to access make the bucket accessible to crawler?

**Comment by undertruck** [comment]
You can give "Full S3 Access" to Crawler IAM role to check if it works. Of course, after that you could secure policy as per your need. It worked for me.

**Comment by tejamuddada** [comment]
i am unable to crawler the json files and unable to create the tables

**Comment by undertruck** [comment]
@tejamuddada : what's the exact error?

**Comment by tejamuddada** [comment]
when i am trying to load the  json files it is not creating exact no of tables as mentioned in example. It is not throwing an error .

**Comment by mukundv** [comment]
Had the same issue, 
Fixed it by creating a custom policy by replacing references to `"aws-glue"` with **`"awsglue"`** and attaching to the role.

**Comment by moomindani** [comment]
> also there's a typo in the s3 path (you have a dot at the end)
> "s3://awsglue-datasets/examples/us-legislators."

Fixed this in https://github.com/aws-samples/aws-glue-samples/commit/c35f722d19ed449e7425aa48ac22d39a2fd646ce.

Currently the developer guide (https://docs.aws.amazon.com/glue/latest/dg/console-crawlers.html) explains how to setup IAM role correctly for crawler. It already covers the issue reported here.

Resolving.

**Comment by jadenguyen0128** [comment]
Just want to share the tutorial where you could point the s3://awsglue-datasets/examples/us-legislators/all using AWS Glue Crawlers

4:48 of youtube.com/watch?v=zdaVBXfmSs0&t=5s

**Comment by xiaomuma99** [comment]
> You can give "Full S3 Access" to Crawler IAM role to check if it works. Of course, after that you could secure policy as per your need. It worked for me.

It works

**Comment by jacksonoh-360f** [comment]
Writing a note that I had to figure this out from https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-python-samples-legislators.html which was a bad experience.

**Comment by ivaramme** [comment]
I added the following to my `datadest` inline policy to get access to the public S3 bucket from the example:

`"arn:aws:s3:::awsglue-datasets/examples/us-legislators/all/*"`

That fixed it for me.
