### ISSUE TITLE
What version of the AWS SDK are you using?

### ISSUE THREAD

**Issue by james-neutron** [aws-samples/aws-glue-samples#21]
I've tried with the `1.11.297` and `2.0 preview` versions and they have a very different API from what your samples show. For example: These versions don't have a `GlueContext` under `com.amazonaws.services.glue`

**Comment by frederic-schmaljohann** [comment]
For now the jar containing the required classes I could find is located here: s3://aws-glue-jes-prod-us-east-1-assets/etl/jars/glue-assembly.jar

Found on https://docs.aws.amazon.com/glue/latest/dg/dev-endpoint-tutorial-repl.html

**Comment by Lempiraholio** [comment]
Is there any way I could download that .jar? I'm losing my mind over the AWS Glue Scala API, it lacks many information.

**Comment by frederic-schmaljohann** [comment]
yes, using the aws cli for example.

aws s3 cp s3://aws-glue-jes-prod-us-east-1-assets/etl/jars/glue-assembly.jar glue-assembly.jar

**Comment by rgduncan** [comment]
I'm unable to download this JAR. Why is this dependency not available in Maven? This makes no sense.

**Comment by mbragg02** [comment]
Hi, is there any update on this? Id like to supply my own library the uses the Glue service APIs and downloading the assembly jar and including it is not really an option.

**Comment by moomindani** [comment]
Glue ETL library is not a part of AWS SDK.
You can follow below steps to develop ETL scripts locally.
https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-libraries.html
