### ISSUE TITLE
Tables created using join_and_relationalize.md example not showing any data

### ISSUE THREAD

**Issue by rbhogi** [aws-samples/aws-glue-samples#22]
As per https://github.com/aws-samples/aws-glue-samples/blob/master/examples/join_and_relationalize.md example, created a crawler with s3://awsglue-datasets/examples/us-legislators. Crawler ran successfully created tables in the database. When I try to retrieve the data from these tables using Athena, I am seeing "Zero records returned." message. More info (Crawler name:aws-glue-samples-raja0505, region:us-east-2)

persons_json
memberships_json
organizations_json
events_json
areas_json
countries_r_json

**Comment by tejamuddada** [comment]
which json files added to glue to create crawler .Do we need to add all the json files or only some specific files to create a crawler as per example i am unable to follow which json files needs to be added to s3 to create crawler.

**Comment by asaushkin** [comment]
I am stuck with the same thing. Tables were inferred without any problem, but when I query it with Athena it shows empty result

![image](https://user-images.githubusercontent.com/471575/90644121-0ac84180-e23d-11ea-88c9-a79c0e49093d.png)
