### ISSUE TITLE
Possible to pull incremental data from Source

### ISSUE THREAD

**Issue by Dboskwi** [aws-samples/aws-glue-samples#27]
Hey

am trying to read incremental data from source. This is Connected using JDBC. I need to pass the timestamp in the filter. Is this a valid usecase if so any documentation is there? Am not able to find any for it.

Thanks

**Comment by moomindani** [comment]
We are sorry for not replying this for long time.
We recommend to ask such questions on AWS Forum instead of creating an issue on GitHub.

Resolving.
