### ISSUE TITLE
Could not configure Spark Submit parameters

### ISSUE THREAD

**Issue by vkrishna1084** [aws-samples/aws-glue-samples#28]
Hi Team,
I'm running an ETL job in AWS glue which reads the table data and process the data and write it to S3. The job is failing with following error message:
ExecutorLostFailure (executor 38 exited caused by one of the running tasks) Reason: Container killed by YARN for exceeding memory limits. 5.5 GB of 5.5 GB physical memory used. Consider boosting spark.yarn.executor.memoryOverhead.

When I tried to modify the memory configurations with --conf parameter, it is not getting reflected in the job execution and the job is still failing with the same error.

When I searched for information online (link given below), it said we could not modify Spark configuration parameters in Glue, can you please confirm? If Yes, can you please provide me any alternatives for a successful execution

https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-glue-arguments.html

Thanks in Advance!

Regards,
Vamshi

**Comment by moomindani** [comment]
We are sorry for not replying this for long time.

After we released Glue worker types, we recommend to change worker type from Standard to G.1X or G.2X if you need much more memory.
https://docs.aws.amazon.com/glue/latest/dg/add-job.html

Hope it helps.
Resolving.
