### ISSUE TITLE
An error occurred while calling o60.getDynamicFrame. Char length 256 out of allowed range [1, 255]

### ISSUE THREAD

**Issue by boriside** [aws-samples/aws-glue-samples#29]
The Error 

`An error occurres while calling o60.getDynamicFrame. Char length 256 out of allowed range [1, 255]`

occurs from

`glueContext.create_dynamic_frame.from_catalog(database=db_name, table_name=my_tbl)`

**Comment by moomindani** [comment]
We are sorry for not responding to this issue for long time.
Are you still seeing the same error?

I would like you to ask this kind of question in AWS Forum instead if your issue is not a bug or feature request for aws-glue-samples repository.
