### ISSUE TITLE
post glue catalog upgrade

### ISSUE THREAD

**Issue by bmardimani** [aws-samples/aws-glue-samples#30]
Hi, I just upgraded to glue data catalog and I could not see any crawlers created on its own. Also, if I want to create a crawler to update an existing table in the catalog, I don't get the option to choose the table of an existing database which it created  as i don't want the crawler to create a new table every time. any help is much appreciated! Thank you

**Comment by moomindani** [comment]
We are sorry for not replying this for a long time.
We recommend to ask such questions in AWS Forum instead of creating an issue on GitHub.

Resolving.
