### ISSUE TITLE
Documentation doesn't mention PyGlue prominently 

### ISSUE THREAD

**Issue by russellpierce** [aws-samples/aws-glue-samples#35]
Given that most of the example python scripts won't work without the awsglue module, perhaps this repo would be more useful for folks if information about awsglue (and how to get it) were presented prominently.  If you are at this issue and wondering where... https://docs.aws.amazon.com/glue/latest/dg/dev-endpoint-tutorial-pycharm.html

**Comment by moomindani** [comment]
Added explanation to README. Resolving.
