### ISSUE TITLE
local execution of aws glue

### ISSUE THREAD

**Issue by BardiaAfshin** [aws-samples/aws-glue-samples#42]
Trying to run aws glue with AWSGlue.zip throws following error

```I have given it a go to do this locally and this is what I get

~/opt/spark-2.2.0-bin-hadoop2.7/bin/pyspark
Python 2.7.15 |Anaconda, Inc.| (default, Dec 14 2018, 13:10:39) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
19/02/18 18:36:18 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
19/02/18 18:36:23 WARN ObjectStore: Failed to get database global_temp, returning NoSuchObjectException
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.2.0
      /_/

Using Python version 2.7.15 (default, Dec 14 2018 13:10:39)
SparkSession available as 'spark'.
>>> from awsglue.dynamicframe import DynamicFrameWriter
>>> glueContext = GlueContext(sc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'GlueContext' is not defined
>>> from awsglue.context import GlueContext
>>> glueContext = GlueContext(sc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "awsglue/context.py", line 44, in __init__
    self._glue_scala_context = self._get_glue_scala_context(**options)
  File "awsglue/context.py", line 64, in _get_glue_scala_context
    return self._jvm.GlueContext(self._jsc.sc())
TypeError: 'JavaPackage' object is not callable
```

**Comment by sherkartejas** [comment]
Hi @BardiaAfshin 
I'm facing the same issue. Did you manage to resolve it?
Thanks.

Cheers x

**Comment by BardiaAfshin** [comment]
No, I have a support ticket from AWS, they basically came back with "this is proprietary issue", but I think that cannot be right answer. You can get their scala package working locally.

**Comment by rashid-1989** [comment]
I am also facing the same issue. Could Aws team provide any solution @BardiaAfshin ?

**Comment by xiaojiang01** [comment]
Did you try to run `./bin/glue-setup.sh` script? This error message means you are missing some java libs in jarv1 folder.

**Comment by rvasconcelossilva** [comment]
Any answers about this issue?

**Comment by rpshgupta** [comment]
Any solution to this?? I am getting same issue.. i am trying to run aws glue on my ubuntu system.. 

ypeError                                 Traceback (most recent call last)
<ipython-input-8-58f892cc6c54> in <module>
----> 1 glueContext = GlueContext(sc)

~/aws-glue-libs-glue-1.0/PyGlue.zip/awsglue/context.py in __init__(self, sparkContext, **options)
     43         super(GlueContext, self).__init__(sparkContext)
     44         register(sparkContext)
---> 45         self._glue_scala_context = self._get_glue_scala_context(**options)
     46         self.create_dynamic_frame = DynamicFrameReader(self)
     47         self.write_dynamic_frame = DynamicFrameWriter(self)

~/aws-glue-libs-glue-1.0/PyGlue.zip/awsglue/context.py in _get_glue_scala_context(self, **options)
     64 
     65         if min_partitions is None:
---> 66             return self._jvm.GlueContext(self._jsc.sc())
     67         else:
     68             return self._jvm.GlueContext(self._jsc.sc(), min_partitions, target_partitions)

TypeError: 'JavaPackage' object is not callable

**Comment by moomindani** [comment]
Recently we have updated the maven repository to solve issues for local development.
Can you try again and check if you still see the issue?

**Comment by kashifmalik-sde** [comment]
Hi moomindani - I just tried it with './bin/gluepyspark' and the result is the below error:

>>> from awsglue.context import GlueContext
>>> glueContext = GlueContext(spark.sparkContext.getOrCreate())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/*****/*****/awsglue/context.py", line 45, in __init__
    self._glue_scala_context = self._get_glue_scala_context(**options)
  File "/Users/****/*****/awsglue/context.py", line 66, in _get_glue_scala_context
    return self._jvm.GlueContext(self._jsc.sc())
TypeError: 'JavaPackage' object is not callable

**Comment by moomindani** [comment]
Today I tried it on the latest Amazon Linux 2 and on my Macbook, and it worked without any errors.

If you still the error, can you describe details?
- Your environment (OS, version, etc.)
- How to replicate the issue
  - e.g. Starting "gluepyspark" command, putting the two lines of code
- Glue version: 1.0 or 0.9
- Check if you followed correct procedures
  - git checkout glue-1.0 (for Glue 1.0)
  - Used correct version of Spark package

**Comment by kashifmalik-sde** [comment]
Thank you @moomindani - In my case, I had the jarsv1 not landing in the correct folder, but once that was fixed, I was able to run the job locally with no issue.

**Comment by mohdaliiqbal** [comment]
> Thank you @moomindani - In my case, I had the jarsv1 not landing in the correct folder, but once that was fixed, I was able to run the job locally with no issue.

that is correct if glue jars were not available in the classpath you will see this error.

**Comment by BardiaAfshin** [comment]
I followed instructions from aws docs - I see that in awslabs there is aws glue repo that has better instructions. BUT - for those wondering what jarsv1 is - like myself coming from aws docs, I followed these instructions and got it to work locally. 

https://support.wharton.upenn.edu/help/glue-debugging#update-path-and-java-home-

**Comment by moomindani** [comment]
It seems that you are not seeing the issue now.
Please reopen this issue if you still see the issue.

**Comment by adamfortuno** [comment]
I'm having the issue described by @BardiaAfshin:

![image](https://user-images.githubusercontent.com/30395811/85074498-a0d2e380-b18a-11ea-9ba1-7e78924fa28d.png)

**NOTE**: I'm running the solution on Windows 10, Python 3.7.3, Spark 2.4.3, and Hadoop 2.8.5.

After launching PySpark, I am running the following:

```python
from awsglue.context import GlueContext
glueContext = GlueContext(sc)
```
The following are the "netty" files in my `..\aws-glue-libs\jarsv1\`:

![image](https://user-images.githubusercontent.com/30395811/85074702-fd360300-b18a-11ea-9308-85546cbdd1a5.png)

Help!
