### ISSUE TITLE
Missing DynamicFrame import

### ISSUE THREAD

**Issue by christopherbertrand** [aws-samples/aws-glue-samples#46]
In examples/data_cleaning_and_lambda.md section **5. Lambda functions (aka Python UDFs) and ApplyMapping**, there's call to `DynamicFrame.fromDF()` on line 222, but it seems like the class DynamicFrame wasn't imported as part of the boiler plater. I added `from awsglue.dynamicframe import DynamicFrame` and everything in the sample worked cleanly. Thanks for all the work on these. They're super helpful

**Comment by moomindani** [comment]
Thanks for reporting it.
It has been fixed by #36.
