### ISSUE TITLE
Join and Relationalize runs forever

### ISSUE THREAD

**Issue by Bashton-MattBuckland** [aws-samples/aws-glue-samples#53]
Hello,

I'm trying to run the `join_and_relationalize.py` example. I let it run for 2h24m before killing it. It just keeps repeating messages like this:

```
19/09/26 20:22:17 DEBUG Client: 
client token: N/A
diagnostics: N/A
ApplicationMaster host: [removed_ip]
ApplicationMaster RPC port: [removed_port]
queue: default
start time: 1569529172541
final status: UNDEFINED
tracking URL: http://ip-[removed].glue.dnsmasq:20888/proxy/application_[removed_id]/
user: root
```

It's creating tables in redshift and populating them, but I would not expect 11MB of data to take 2.5h to process.

Any idea how to make it work?

Thanks,

Matt

**Comment by papayuca** [comment]
+1
I had a similar situation, it worked properly for a while, and then just stopped working, i.e. started hanging forever with the same repeating message.

**Comment by moomindani** [comment]
Unfortunately I was not able to replicate the same issue in my end.
Please reopen or ask in AWS Forum if you still see the issue.
