### ISSUE TITLE
sample code missing import library

### ISSUE THREAD

**Issue by smylere** [aws-samples/aws-glue-samples#57]
Data cleaning with AWS Glue
(aws-glue-samples/examples/data_cleaning_and_lambda.md)

not include awsglue.DynamicFrame syntax

check plz insert DynamicFrame class 

**from awsglue.dynamicframe import DynamicFrame**

ex)
medicare_tmp_dyf = DynamicFrame.fromDF(medicare_dataframe, glueContext, "nested")

**Comment by moomindani** [comment]
Thanks for reporting it.
It has been fixed by https://github.com/aws-samples/aws-glue-samples/pull/36.
