### ISSUE TITLE
Issue while accessing GlueContext locally

### ISSUE THREAD

**Issue by roshni0107** [aws-samples/aws-glue-samples#59]
Hi,

To develop ETL Scripts locally with Python I have followed below steps :-

1.	Downloaded the AWS Glue Python library from GitHub. For Glue version 1.0, I checked out branch glue-1.0 as this version supports Python 3.
2.	Installed Apache Maven and referenced the path of Maven in the environment variables.
3.	Installed the Apache Spark and set the SPARK_HOME in environment variables
4.	Installed jdk and set the JAVA_HOME in environment variables
5.	Installed Hadoop and set HADOOP_HOME in environment variables
6.	Installed pyspark, awscli and boto3.

I chose the ETL script that was automatically generated by AWS glue and ran the job.
It worked successfully from AWS console and the file from source was loaded into the destination folder. But when I try to execute the same script locally, I encountered below error:

**return self._jvm.GlueContext(self._jsc.sc())
TypeError: 'JavaPackage' object is not callable**
 
Is there any workaround for this?

Thanks

**Comment by rvasconcelossilva** [comment]
@roshni0107 did you get it?

**Comment by moomindani** [comment]
Recently we have updated the maven repository to solve issues for local development.
Can you try again and check if you still see the issue?

**Comment by moomindani** [comment]
Today I tried it on the latest Amazon Linux 2 and on my Macbook, and it worked without any errors.

If you still the error, can you describe details?
- Your environment (OS, version, etc.)
- How to replicate the issue
  - e.g. Starting "gluepyspark" command, putting the two lines of code
- Glue version: 1.0 or 0.9
- Check if you followed correct procedures
  - git checkout glue-1.0 (for Glue 1.0)
  - Used correct version of Spark package

**Comment by moomindani** [comment]
Since there are no updates for one month, I am resolving this issue.
Please reopen this issue if you still see the error.
