### ISSUE TITLE
Bad coding practices (Python)

### ISSUE THREAD

**Issue by 1oglop1** [aws-samples/aws-glue-samples#62]
This and awslabs are full of bad practices which people unfortunately copy over because they use this as an example.

Would you consider connecting this repository to some linters or codeac.io?
To prevent spreading bad practices.

example: 
https://github.com/aws-samples/aws-glue-samples/blob/master/examples/join_and_relationalize.py#L5

`from x import *` - is an anti pattern which might lead to unexpected behaviour and also makes reading the code much harder because it's unsure where the functions come from. 

more info: https://www.flake8rules.com/rules/F405.html

>Namespaces are one honking great idea -- let's do more of those! "Zen of python"

**Comment by moomindani** [comment]
Thank you for your kind feedback.
We have modified it in https://github.com/aws-samples/aws-glue-samples/commit/2a0e75659b2a4f95b473dddd08c55cfd27b73257.
