### ISSUE TITLE
Spark_UI docker container-Error: Could not find or load main class $SPARK_HISTORY_OPTS

### ISSUE THREAD

**Issue by Eric0720** [aws-samples/aws-glue-samples#64]
1.docker build -t glue/sparkui:latest . 
2.docker run -itd -e SPARK_HISTORY_OPTS="$SPARK_HISTORY_OPTS -Dspark.history.fs.logDirectory=s3a://test/sparkui -Dspark.hadoop.fs.s3a.access.key=xxxxxx -Dspark.hadoop.fs.s3a.secret.key=yyyyyyy" -p 18080:18080 glue/sparkui:latest "/opt/spark/bin/spark-class org.apache.spark.deploy.history.HistoryServer"

hi,when I run the second step, it prompts me Could not find or load main class $SPARK_HISTORY_OPTS，I have no way solve it

**Comment by sardetushar** [comment]
How did you solve this ?

**Comment by tonygyerr** [comment]
What was the solution? The issues is closed with no solution.

**Comment by avinash-03** [comment]
see this [stackoverflow answer](https://stackoverflow.com/questions/63788008/spark-aws-glue-ui-error-could-not-find-or-load-main-class-spark-history-opts)
