### ISSUE TITLE
Library dependency broken May 5, 2020

### ISSUE THREAD

**Issue by JeremyDOwens** [aws-samples/aws-glue-samples#65]
Good Afternoon,

I am not certain that this is the right place for this issue. If someone knows better, please point me to the right location. I have a simple example project for testing locally in Scala, and have been using the AWSGlueETL library. As of this afternoon, it has stopped working.

You can see the error here:  
https://github.com/Gamesight/aws-glue-local-scala/runs/647153542?check_suite_focus=true

It looks like the file was changed today:   
```
<Contents>
<Key>
release/com/amazonaws/AWSGlueETL/1.0.0/AWSGlueETL-1.0.0.pom
</Key>
<LastModified>2020-05-05T16:53:39.000Z</LastModified>
<ETag>"05ec2f9f20bc535e4d00717fe1c902bf"</ETag>
<Size>17464</Size>
<StorageClass>STANDARD</StorageClass>
</Contents>
```

Upon inspection of the file: https://aws-glue-etl-artifacts.s3.amazonaws.com/release/com/amazonaws/AWSGlueETL/1.0.0/AWSGlueETL-1.0.0.pom  

I see this:
```
 <properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <encoding>UTF-8</encoding>
    <scala.version>2.11.1</scala.version>
    <scala.compat.version>2.11</scala.compat.version>
    <spec2.version>4.2.0</spec2.version>
    <glue.artifacts.bucket>aws-glue-etl-artifacts-beta</glue.artifacts.bucket>
    <glue.sdk.artifactid>AWSSDKGlueJavaClient</glue.sdk.artifactid>
    <glue.sdk.version>1.0</glue.sdk.version>
    <aws.sdk.version>1.11.774</aws.sdk.version>
  </properties>
```

It looks like the `glue.sdk.artifactid` may be referencing a java class instead of the usual `aws-java-sdk-glue` or maybe the beta flag in the reference to aws-glue-etl-artifacts-beta bucket wasn't removed? It  doesn't appear that public access is enabled for that bucket. Whatever the cause, the AWSSDKGlueJavaClient file is not there.

Any help would be appreciated.

**Comment by slavokx** [comment]
Hello, 
I am experiencing very same issue since yesterday, so far i have not found any workaround.

**Comment by slavokx** [comment]
looks like amazon fixed the issue, it is working now

**Comment by JeremyDOwens** [comment]
Nice! It looks like the error was just where we thought it was:
```
<properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <encoding>UTF-8</encoding>
    <scala.version>2.11.1</scala.version>
    <scala.compat.version>2.11</scala.compat.version>
    <spec2.version>4.2.0</spec2.version>
    <glue.artifacts.bucket>aws-glue-etl-artifacts</glue.artifacts.bucket>
    <aws.sdk.version>1.11.774</aws.sdk.version>
    <glue.sdk.artifactid>aws-java-sdk-glue</glue.sdk.artifactid>
    <glue.sdk.version>${aws.sdk.version}</glue.sdk.version>
  </properties>
```
the reference is fixed in the pom file!
