### ISSUE TITLE
does ML transform support model versioning? Can you specify this in FindMatches?

### ISSUE THREAD

**Issue by BardiaAfshin** [aws-samples/aws-glue-samples#68]
Can you reference which version of a trained ML Transform to use when running FindMatches?
example:
Train model with labels - version 1
Train model with more labels - version 2

Is there a way to specify in FindMatches to look for duplicates via -version 1 even though on the same ML Transform job you have already ran additional labels for tuning the model for version 2?

Sum it up, A vs B test on the same ML Transform job.

**Comment by moomindani** [comment]
Thank you for using AWS Glue. Sorry for delay.
This repository is for hosting samples related to AWS Glue.
Your question does not depend on the samples.

I would like you to ask in AWS Forum or AWS Premium support.
Resolving.
