### ISSUE TITLE
How to start Crawler at the end of a job?

### ISSUE THREAD

**Issue by HammadAWS** [aws-samples/aws-glue-samples#7]
I want AWS Glue job to start the crawler at the end of the job.
Can anyone share python script that I will put at the end of the job to do that?

**Comment by cmoore-wts** [comment]
import boto3
glue_client = boto3.client('glue',  region_name='us-east-1')
glue_client.start_crawler(Name='name_of_crawler')

**Comment by moomindani** [comment]
Currently you can take advantage of Glue workflow.
See details in below doc. https://docs.aws.amazon.com/glue/latest/dg/orchestrate-using-workflows.html

Resolving.
