### ISSUE TITLE
Reading Avro files in Glue version 1

### ISSUE THREAD

**Issue by vamsikt** [aws-samples/aws-glue-samples#71]
Hi,
I am using [Glue version 1](https://docs.aws.amazon.com/glue/latest/dg/release-notes.html) which supports Spark 2.4.3 and want to use Spark Avro to read some Avro files.

How to pass the spark Avro package in glue spark-submit (https://spark.apache.org/docs/2.4.3/sql-data-sources-avro.html)

**Comment by moomindani** [comment]
Thank you for using AWS Glue.
This repository is for hosting samples related to AWS Glue.
Your question does not depend on the samples.

I would like you to ask in AWS Forum or AWS Premium support.
Resolving.
