### ISSUE TITLE
README -- what should env var SPARK_HISTORY_OPTS be set as? It's undefined.

### ISSUE THREAD

**Issue by ctivanovich** [aws-samples/aws-glue-samples#80]
I'm new to spark by and large, sorry if there is an obvious answer, but I don't see a value provided in the README, though it's listed as a variable to be passed to the docker command at container launch.

**Comment by moomindani** [comment]
Hi, it is okay to use empty $SPARK_HISTORY_OPTS if you do not have any preferences.
It is just in order not to lose customized options when you have them.
