### ISSUE TITLE
Problem with the hive_metastore_migration Script

### ISSUE THREAD

**Issue by sargofco72** [aws-samples/aws-glue-samples#85]
Hi, Im trying to migrate my Hive Metastore on RDS MySql to Aws Glue Datacatalog, I've configured all parameters like the guide show and after some minutes the Jod end on error with the following message:

SyntaxError: invalid syntax (hive_metastore_migration.py, line 326)

This line into the script is 

        return self.sql_context.createDataFrame(
            df.rdd.map(lambda row: (row[id_col], {row[key]: row[value]})).reduceByKey(merge_dict).map(
                lambda (id_name, dictionary): (id_name, remove_none_key(dictionary))), output_schema)

I've used the following configuration for my Glue Job:

Type:Spark
Glue version:  Glue 1.0 - Supports Spark 2.4, Scala 2, Python 3
Language: Python 3
Worker Type: G.1X
Maximum concurrency: 1

and te parameters that you are indicated.

Into the logs, this is the error 

Container: container_1614944659771_0001_01_000001 on ip-10-197-19-160.glue.dnsmasq_8041=========================================================================================LogType:stderrLog Upload Time:Fri Mar 05 11:49:06 +0000 2021LogLength:5003Log Contents:SLF4J: Class path contains multiple SLF4J bindings.SLF4J: Found binding in [jar:file:/mnt/yarn/usercache/root/filecache/11/glue-assembly.jar!/org/slf4j/impl/StaticLoggerBinder.class]SLF4J: Found binding in [jar:file:/mnt/yarn/usercache/root/filecache/22/__spark_libs__8962282988460139001.zip/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]21/03/05 11:49:02 INFO SignalUtils: Registered signal handler for TERM21/03/05 11:49:02 INFO SignalUtils: Registered signal handler for HUP21/03/05 11:49:02 INFO SignalUtils: Registered signal handler for INT21/03/05 11:49:02 INFO SecurityManager: Changing view acls to: yarn,root21/03/05 11:49:02 INFO SecurityManager: Changing modify acls to: yarn,root21/03/05 11:49:02 INFO SecurityManager: Changing view acls groups to: 21/03/05 11:49:02 INFO SecurityManager: Changing modify acls groups to: 21/03/05 11:49:02 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(yarn, root); groups with view permissions: Set(); users  with modify permissions: Set(yarn, root); groups with modify permissions: Set()21/03/05 11:49:02 WARN Configuration: __spark_hadoop_conf__.xml:an attempt to override final parameter: fs.s3.buffer.dir;  Ignoring.21/03/05 11:49:02 WARN Configuration: __spark_hadoop_conf__.xml:an attempt to override final parameter: fs.s3.buffer.dir;  Ignoring.21/03/05 11:49:02 WARN Configuration: __spark_hadoop_conf__.xml:an attempt to override final parameter: yarn.nodemanager.local-dirs;  Ignoring.21/03/05 11:49:02 WARN Configuration: __spark_hadoop_conf__.xml:an attempt to override final parameter: fs.s3.buffer.dir;  Ignoring.21/03/05 11:49:02 WARN Configuration: __spark_hadoop_conf__.xml:an attempt to override final parameter: yarn.nodemanager.local-dirs;  Ignoring.21/03/05 11:49:02 INFO ApplicationMaster: Preparing Local resources21/03/05 11:49:03 WARN Configuration: __spark_hadoop_conf__.xml:an attempt to override final parameter: fs.s3.buffer.dir;  Ignoring.21/03/05 11:49:03 WARN Configuration: __spark_hadoop_conf__.xml:an attempt to override final parameter: yarn.nodemanager.local-dirs;  Ignoring.21/03/05 11:49:03 INFO ApplicationMaster: ApplicationAttemptId: appattempt_1614944659771_0001_00000121/03/05 11:49:03 INFO ApplicationMaster: Starting the user application in a separate Thread21/03/05 11:49:03 INFO ApplicationMaster: Waiting for spark context initialization...21/03/05 11:49:04 ERROR ApplicationMaster: User application exited with status 121/03/05 11:49:04 INFO ApplicationMaster: Final app status: FAILED, exitCode: 13, (reason: User application exited with status 1)21/03/05 11:49:04 ERROR ApplicationMaster: Uncaught exception: org.apache.spark.SparkException: Exception thrown in awaitResult: 	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:226)	at org.apache.spark.deploy.yarn.ApplicationMaster.runDriver(ApplicationMaster.scala:468)	at org.apache.spark.deploy.yarn.ApplicationMaster.org$apache$spark$deploy$yarn$ApplicationMaster$$runImpl(ApplicationMaster.scala:305)	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply$mcV$sp(ApplicationMaster.scala:245)	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply(ApplicationMaster.scala:245)	at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply(ApplicationMaster.scala:245)	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:779)	at java.security.AccessController.doPrivileged(Native Method)	at javax.security.auth.Subject.doAs(Subject.java:422)	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroup | Container: container_1614944659771_0001_01_000001 on ip-10-197-19-160.glue.dnsmasq_8041 ========================================================================================= LogType:stderr Log Upload Time:Fri Mar 05 11:49:06 +0000 2021 LogLength:5003 Log Contents: SLF4J: Class path contains multiple SLF4J bindings. SLF4J: Found binding in [jar:file:/mnt/yarn/usercache/root/filecache/11/glue-assembly.jar!/org/slf4j/impl/StaticLoggerBinder.class] SLF4J: Found binding in [jar:file:/mnt/yarn/usercache/root/filecache/22/__spark_libs__8962282988460139001.zip/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class] SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation. SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory] 21/03/05 11:49:02 INFO SignalUtils: Registered signal handler for TERM 21/03/05 11:49:02 INFO SignalUtils: Registered signal handler for HUP 21/03/05 11:49:02 INFO SignalUtils: Registered signal handler for INT 21/03/05 11:49:02 INFO SecurityManager: Changing view acls to: yarn,root 21/03/05 11:49:02 INFO SecurityManager: Changing modify acls to: yarn,root 21/03/05 11:49:02 INFO SecurityManager: Changing view acls groups to: 21/03/05 11:49:02 INFO SecurityManager: Changing modify acls groups to: 21/03/05 11:49:02 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(yarn, root); groups with view permissions: Set(); users with modify permissions: Set(yarn, root); groups with modify permissions: Set() 21/03/05 11:49:02 WARN Configuration: __spark_hadoop_conf__.xml:an attempt to override final parameter: fs.s3.buffer.dir; Ignoring. 21/03/05 11:49:02 WARN Configuration: __spark_hadoop_conf__.xml:an attempt to override final parameter: fs.s3.buffer.dir; Ignoring. 21/03/05 11:49:02 WARN Configuration: __spark_hadoop_conf__.xml:an attempt to override final parameter: yarn.nodemanager.local-dirs; Ignoring. 21/03/05 11:49:02 WARN Configuration: __spark_hadoop_conf__.xml:an attempt to override final parameter: fs.s3.buffer.dir; Ignoring. 21/03/05 11:49:02 WARN Configuration: __spark_hadoop_conf__.xml:an attempt to override final parameter: yarn.nodemanager.local-dirs; Ignoring. 21/03/05 11:49:02 INFO ApplicationMaster: Preparing Local resources 21/03/05 11:49:03 WARN Configuration: __spark_hadoop_conf__.xml:an attempt to override final parameter: fs.s3.buffer.dir; Ignoring. 21/03/05 11:49:03 WARN Configuration: __spark_hadoop_conf__.xml:an attempt to override final parameter: yarn.nodemanager.local-dirs; Ignoring. 21/03/05 11:49:03 INFO ApplicationMaster: ApplicationAttemptId: appattempt_1614944659771_0001_000001 21/03/05 11:49:03 INFO ApplicationMaster: Starting the user application in a separate Thread 21/03/05 11:49:03 INFO ApplicationMaster: Waiting for spark context initialization... 21/03/05 11:49:04 ERROR ApplicationMaster: User application exited with status 1 21/03/05 11:49:04 INFO ApplicationMaster: Final app status: FAILED, exitCode: 13, (reason: User application exited with status 1) 21/03/05 11:49:04 ERROR ApplicationMaster: Uncaught exception: org.apache.spark.SparkException: Exception thrown in awaitResult: at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:226) at org.apache.spark.deploy.yarn.ApplicationMaster.runDriver(ApplicationMaster.scala:468) at org.apache.spark.deploy.yarn.ApplicationMaster.org$apache$spark$deploy$yarn$ApplicationMaster$$runImpl(ApplicationMaster.scala:305) at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply$mcV$sp(ApplicationMaster.scala:245) at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply(ApplicationMaster.scala:245) at org.apache.spark.deploy.yarn.ApplicationMaster$$anonfun$run$1.apply(ApplicationMaster.scala:245) at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:779) at java.security.AccessController.doPrivileged(Native Method) at javax.security.auth.Subject.doAs(Subject.java:422) at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1844)
	at org.apache.spark.deploy.yarn.ApplicationMaster.doAsUser(ApplicationMaster.scala:778)
	at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:244)
	at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:803)
	at org.apache.spark.deploy.yarn.ApplicationMaster.main(ApplicationMaster.scala)
Caused by: org.apache.spark.SparkUserAppException: User application exited with 1
	at org.apache.spark.deploy.PythonRunner$.main(PythonRunner.scala:106)
	at org.apache.spark.deploy.PythonRunner.main(PythonRunner.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:684)
21/03/05 11:49:04 INFO ApplicationMaster: Deleting staging directory hdfs://10.197.19.203:8020/user/root/.sparkStaging/application_1614944659771_0001
21/03/05 11:49:04 INFO ShutdownHookManager: Shutdown hook called
End of LogType:stderr

LogType:stdout
Log Upload Time:Fri Mar 05 11:49:06 +0000 2021
LogLength:515
Log Contents:
Parse yarn logs get error message:  SyntaxError: invalid syntax (hive_metastore_migration.py, line 326)
Traceback (most recent call last):
  File "script_2021-03-05-11-47-48.py", line 9, in <module>
    from hive_metastore_migration import *
  File "/mnt/yarn/usercache/root/appcache/application_1614944659771_0001/container_1614944659771_0001_01_000001/__pyfiles__/hive_metastore_migration.py", line 326
    lambda (id_name, dictionary): (id_name, remove_none_key(dictionary))), output_schema)
           ^
SyntaxError: invalid syntax
End of LogType:stdout

**Comment by rotemironsrc** [comment]
use Python 2 instead of Python 3
and it will work.
