### ISSUE TITLE
Spark_UI: container terminates with code 127

### ISSUE THREAD

**Issue by a-vico** [aws-samples/aws-glue-samples#87]
Following the steps I build the image without a problem:
`docker build -t glue/sparkui:latest . `

But when I want to launch the container:
`docker run -itd -e \
    SPARK_HISTORY_OPTS="$SPARK_HISTORY_OPTS -Dspark.history.fs.logDirectory=$LOG_DIR -Dspark.hadoop.fs.s3a.access.key=$AWS_ACCESS_KEY_ID -Dspark.hadoop.fs.s3a.secret.key=$AWS_SECRET_ACCESS_KEY -Dspark.hadoop.fs.s3a.session.token=$SESSION_TOKEN -Dspark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.TemporaryAWSCredentialsProvider" \
    -p 18080:18080 glue/sparkui:latest "/opt/spark/bin/spark-class org.apache.spark.deploy.history.HistoryServer"`

It exits inmediatly with code 127, showing this message:
`/bin/bash: C:/Program: No such file or directory`

![image](https://user-images.githubusercontent.com/82828902/115265342-6b46b000-a137-11eb-84d4-1a9e61bbb922.png)

**Comment by GKubaG** [comment]
Did you solve it?

**Comment by moomindani** [comment]
We apologize for delay. Are you still seeing the issue with the latest files?

**Comment by moomindani** [comment]
For now, we close this issue since there are no other reports.
Please reopen if you still see the issue with the latest Dockerfile.

**Comment by Mayurg6832** [comment]
Found a workaround
1. Remove/Comment `ENTRYPOINT ["/bin/bash", "-c"]:` from Dockerfile
2. Run the command 
`docker run -it -e SPARK_HISTORY_OPTS="$SPARK_HISTORY_OPTS -Dspark.history.fs.logDirectory=$LOG_DIR -Dspark.hadoop.fs.s3a.access.key=$AWS_ACCESS_KEY_ID -Dspark.hadoop.fs.s3a.secret.key=$AWS_SECRET_ACCESS_KEY -Dspark.hadoop.fs.s3a.session.token=$AWS_SESSION_TOKEN -Dspark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.TemporaryAWSCredentialsProvider" -p 18080:18080 glue/sparkui:latest "bash"`
3. Run the command from inside the container
` /opt/spark/bin/spark-class org.apache.spark.deploy.history.HistoryServer`
