### ISSUE TITLE
Spark history server: README.md to show using AWS_PROFILE

### ISSUE THREAD

**Issue by wrschneider** [aws-samples/aws-glue-samples#96]
This worked for me:

```
docker run -itd -v /home/username/.aws:/root/.aws -e AWS_PROFILE=profile -e SPARK_HISTORY_OPTS="$SPARK_HISTORY_OPTS -Dspark.history.fs.logDirectory=s3a://path_to_eventlog -Dspark.hadoop.fs.s3a.aws.credentials.provider=com.amazonaws.auth.DefaultAWSCredentialsProviderChain" .... 
```

instead of specifying access key/secret key etc. individually, this specifies the current AWS_PROFILE and exposes the current ~/.aws/credentials file into the docker container.

**Comment by tb102122** [comment]
Yes I can see via ```cat /root/.aws/credentials``` and ```cat /root/.aws/config``` the related files.
But I still get the error could it be some permissions on the file mounting?
Below the result I get:

```
ls -l /root/.aws/
total 0
-rwxrwxrwx 1 root root 2331 Sep 18 23:57 config
-rwxrwxrwx 1 root root  734 Mar 25  2021 credentials
```

**Comment by moomindani** [comment]
@tb102122 Can you share the error messages? Is it the same error as the one you reported?

**Comment by moomindani** [comment]
Yes, I mean add your access key and secret key to the `~/.aws/credentials` file and use it, and remove `source_profile` from YYYY profile in `~/.aws/config`.

**Comment by tb102122** [comment]
yes that's what I have, as I wrote before the regular AWS CLI is working correctly.
The only special part I have in the config is that I need to use a role_arn in my [profile YYYY]

**Comment by moomindani** [comment]
This utility uses AWS SDK for Java v1. Per the above issue, it won't work with role_arn and source_profile.
Can you try setting static IAM user credential in the credential file?

**Comment by tb102122** [comment]
Unfortunately I am not able to do that in this account due to client requirements.

**Comment by moomindani** [comment]
Yes, but there is dependency in hadoop-aws library and AWS SDK for Java.
It will be better for you to go with CloudFormation way for now.

Regarding the original request of this issue, I added it to README. Thanks for the feedback. Resolving.
https://github.com/aws-samples/aws-glue-samples/commit/a156a3185a5ef1fd349d36cd46747f95926ee0b2

**Comment by tb102122** [comment]
sure no problem regarding the readme, I would suggest a note/comment that it does work with role_arn and source_profile in the profile.
